//! Contains constants and data used by this tool to generate the initial cargo package.

/// External crate versions
pub(crate) const WINDOWS_RS_VERSION: &str = "0.18.0";

/// Rust toolchain related assets
pub(crate) const RUST_TOOLCHAIN_TOML_FILENAME: &str = "rust-toolchain.toml";
pub(crate) const RUST_TOOLCHAIN_TOML: &[u8] = include_bytes!("../data/rust-toolchain.toml");

/// Cargo default configuration
pub(crate) const CARGO_CONFIG_DIR: &str = ".cargo";
pub(crate) const CARGO_CONFIG_TOML_FILENAME: &str = "config.toml";
pub(crate) const CARGO_CONFIG_TOML: &[u8] = include_bytes!("../data/.cargo/config.toml");

/// Package metatdata used by the build system and this tool
pub(crate) const PACKAGE_METADATA_INIT: &str = r#"

# Metadata driving the build system. Once created, you can freely fill in and change the
# required entries, and have the build system take it from there.

[package.metadata.appxmanifest]
## The following entries relate to the package identity. They are available through the
## [Microsoft Partner Center](https://partner.microsoft.com) dashboard, once you have
## registered a product name. Go to Products -> <product name> -> Product management ->
## Product Identity to find the respective information.

## The package name (String, required): The value can be found under the key
## "Package/Identity/Name".

# package-identity-name = "nnnnnPublisher.name"

## The package publisher (String, required): The value can be found under the key
## "Package/Identity/Publisher".

# package-identity-publisher = "CN=<guid>"

## The package version (String, optional): A string of four period-delimited numeric
## values following the pattern "<Major>.<Minor>.<Build>.<Revision>". This is the public-
## facing version, that is displayed in the Microsoft Store. It is also used to name
## binary artifacts generated by the build system.
## When missing, this value is substituted with the "version" entry of the [package]
## table, with the <Revision> field defaulting to 0.

# package-identity-version = "0.0.0.0"


## The following entry controls whether to target Windows 10 Mobile.
## The phone product ID (String, optional): A string representing the GUID of the Windows
## 10 Mobile product. It is required when targeting Windows 10 Mobile.
## When missing, no packages targeting Windows 10 Mobile are generated.

# package-phoneidentity-productid = "00000000-0000-0000-0000-000000000000"


## The final two entries designate public-facing properties of the application. Either one
## is displayed in the Microsoft Store.

## The package display name (String, optional): This property must match the application
## name as registered in the Microsoft Partner Center. When missing, this value is
## substituted with the "name" entry of the [package] table.

# package-properties-displayname = "<app name>"

## The package publisher display name (String, required): This property must match the
## publisher display name under which you plan to publish an application in the Microsoft
## Store. Depending on your Microsoft Partner Center registration this information can be
## found under Account settings -> Organization profile -> Legal -> Contact info.

# package-properties-publisherdisplayname = "<publisher name>"

"#;

/// Bindings crate
pub(crate) const BINDINGS_CRATE_PATH: &str = "bindings";
pub(crate) const BINDINGS_CARGO_TOML: &str = include_str!("../data/bindings/Cargo.toml");
pub(crate) const BINDINGS_BUILD_RS: &[u8] = include_bytes!("../data/bindings/build.rs");
pub(crate) const BINDINGS_SRC_LIB_RS: &[u8] = include_bytes!("../data/bindings/src/lib.rs");

/// Placeholders that get replaced during various operations, when copying from templates
/// to the final artifacts.
pub(crate) const WINDOWS_RS_VERSION_PLACEHOLDER: &str = "$windows-rs-version$";
